
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name @NOME@;

    ssl_certificate /etc/letsencrypt/live/@NOME@/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/@NOME@/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_session_cache shared:amaview_blocos:10m;

    include snippets/amaview-blocos.conf;
    include snippets/amaview-fumaca.conf;
    include snippets/amaview-ar.conf;
    include snippets/amaview-meteo.conf;
}
